//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SISMEntities : DbContext
    {
        public SISMEntities()
            : base("name=SISMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblCarreras> TblCarreras { get; set; }
        public virtual DbSet<TblCatalogoContratos> TblCatalogoContratos { get; set; }
        public virtual DbSet<TblColonia> TblColonia { get; set; }
        public virtual DbSet<TblDepartamento> TblDepartamento { get; set; }
        public virtual DbSet<TblDocumentos> TblDocumentos { get; set; }
        public virtual DbSet<TblEmpleado> TblEmpleado { get; set; }
        public virtual DbSet<TblEscuela> TblEscuela { get; set; }
        public virtual DbSet<TblEstado> TblEstado { get; set; }
        public virtual DbSet<TblEstudiosEmpleado> TblEstudiosEmpleado { get; set; }
        public virtual DbSet<TblHijos> TblHijos { get; set; }
        public virtual DbSet<TblKardex> TblKardex { get; set; }
        public virtual DbSet<TblKardexRHyNom> TblKardexRHyNom { get; set; }
        public virtual DbSet<TblMunicipio> TblMunicipio { get; set; }
        public virtual DbSet<TblNivelAcademico> TblNivelAcademico { get; set; }
        public virtual DbSet<TblPais> TblPais { get; set; }
        public virtual DbSet<TblPuesto> TblPuesto { get; set; }
        public virtual DbSet<TblRegimen> TblRegimen { get; set; }
        public virtual DbSet<TblTallasUniformes> TblTallasUniformes { get; set; }
        public virtual DbSet<TblUniforme> TblUniforme { get; set; }
    
        public virtual ObjectResult<SpReporteRetardos_Result> SpReporteRetardos(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFinal)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("FechaFinal", fechaFinal) :
                new ObjectParameter("FechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpReporteRetardos_Result>("SpReporteRetardos", fechaInicioParameter, fechaFinalParameter);
        }
    }
}
