//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltaUrgencias
    {
        public int id { get; set; }
        public string numexp { get; set; }
        public string medico { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public string motivo { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string ip_realiza { get; set; }
        public string usuario_registra { get; set; }
        public string nota { get; set; }
        public Nullable<System.DateTime> fecha_nota { get; set; }
        public string nota_atla { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
    }
}
