//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_Almacen : DbContext
    {
        public BD_Almacen()
            : base("name=BD_Almacen")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SISM_BORRADOR_REQUI> SISM_BORRADOR_REQUI { get; set; }
        public virtual DbSet<SISM_CODIGOBARRAS> SISM_CODIGOBARRAS { get; set; }
        public virtual DbSet<SISM_COSTEO_LICITACION> SISM_COSTEO_LICITACION { get; set; }
        public virtual DbSet<SISM_COTIZACIONES> SISM_COTIZACIONES { get; set; }
        public virtual DbSet<SISM_DET_REQUISICION> SISM_DET_REQUISICION { get; set; }
        public virtual DbSet<SISM_DET_VALE_ENTRADA> SISM_DET_VALE_ENTRADA { get; set; }
        public virtual DbSet<SISM_DETALLE_BORRADOR_REQUI> SISM_DETALLE_BORRADOR_REQUI { get; set; }
        public virtual DbSet<SISM_DETALLE_OC> SISM_DETALLE_OC { get; set; }
        public virtual DbSet<SISM_DETALLE_REQ_FARMACIA> SISM_DETALLE_REQ_FARMACIA { get; set; }
        public virtual DbSet<SISM_INV_MED> SISM_INV_MED { get; set; }
        public virtual DbSet<SISM_MOV_INV> SISM_MOV_INV { get; set; }
        public virtual DbSet<SISM_ORDEN_COMPRA> SISM_ORDEN_COMPRA { get; set; }
        public virtual DbSet<SISM_REQUISICION> SISM_REQUISICION { get; set; }
        public virtual DbSet<SISM_REQUISICION_FARMACIA> SISM_REQUISICION_FARMACIA { get; set; }
        public virtual DbSet<SISM_VALE_ENTRADA> SISM_VALE_ENTRADA { get; set; }
    }
}
