//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class captured_columns
    {
        public int object_id { get; set; }
        public string column_name { get; set; }
        public Nullable<int> column_id { get; set; }
        public string column_type { get; set; }
        public int column_ordinal { get; set; }
        public Nullable<bool> is_computed { get; set; }
        public string masking_function { get; set; }
    }
}
