//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizaciones
    {
        public int Id { get; set; }
        public int Id_Sustancia { get; set; }
        public int Id_Requisicion { get; set; }
        public Nullable<int> Id_Prov_1 { get; set; }
        public Nullable<int> Cant_Asig_1 { get; set; }
        public Nullable<double> CostoUnit_1 { get; set; }
        public Nullable<int> Id_Prov_2 { get; set; }
        public Nullable<int> Cant_Asig_2 { get; set; }
        public Nullable<double> CostoUnit_2 { get; set; }
        public Nullable<int> Id_Prov_3 { get; set; }
        public Nullable<int> Cant_Asig_3 { get; set; }
        public Nullable<double> CostoUnit_3 { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public Nullable<int> Cuadro { get; set; }
    }
}
