//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CovidSolicitud
    {
        public int SolicitudId { get; set; }
        public string NumEmp { get; set; }
        public string Medico { get; set; }
        public string Nota { get; set; }
        public System.DateTime FechaSol { get; set; }
        public bool Vacunado { get; set; }
        public string MarcaVacuna { get; set; }
        public Nullable<bool> EsquemaCompleto { get; set; }
        public Nullable<System.DateTime> FechaUltimaDosis { get; set; }
        public Nullable<bool> Fiebre { get; set; }
        public Nullable<bool> Tos { get; set; }
        public Nullable<bool> Anosmia { get; set; }
        public Nullable<bool> Hipotension { get; set; }
        public Nullable<bool> Odinofagia { get; set; }
        public Nullable<bool> Mialgia { get; set; }
        public Nullable<bool> FRM25 { get; set; }
        public Nullable<bool> AlteracionConsciencia { get; set; }
        public Nullable<bool> DolorCabeza { get; set; }
        public Nullable<bool> DolorAbdominal { get; set; }
        public Nullable<bool> Disnea { get; set; }
        public Nullable<bool> Saturacion { get; set; }
        public Nullable<bool> Alteraciones { get; set; }
        public Nullable<bool> Diarrea { get; set; }
        public Nullable<bool> Mareo { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaAgenda { get; set; }
        public string UsuarioAgenda { get; set; }
        public string UsuarioRealiza { get; set; }
        public Nullable<System.DateTime> FechaRealiza { get; set; }
        public string NotaRealiza { get; set; }
        public bool Finalizado { get; set; }
        public bool Cancelado { get; set; }
        public bool NoPresento { get; set; }
        public string Urgente { get; set; }
        public Nullable<int> Resultado { get; set; }
        public string NotaResultado { get; set; }
        public Nullable<System.DateTime> FechaResultado { get; set; }
        public string UsuarioResultado { get; set; }
        public Nullable<bool> Rinorrea { get; set; }
        public Nullable<bool> Diarrea16 { get; set; }
        public Nullable<bool> Ictericia { get; set; }
        public Nullable<bool> Acolia { get; set; }
        public Nullable<bool> Coluria { get; set; }
        public Nullable<bool> chkGanglios { get; set; }
        public Nullable<bool> chkExantema { get; set; }
    }
}
