//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleReq
    {
        public int Id { get; set; }
        public int Id_Requisicion { get; set; }
        public int Id_Sustancia { get; set; }
        public int C_Solicitada { get; set; }
        public Nullable<int> C_Recibida { get; set; }
        public bool Status { get; set; }
    
        public virtual Requisicion_1 Requisicion { get; set; }
    }
}
