//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOC
    {
        public int Id { get; set; }
        public int Id_OrdenCompra { get; set; }
        public int Id_CodigoBarras { get; set; }
        public int Cantidad { get; set; }
        public double PreUnit { get; set; }
        public Nullable<int> Obsequio { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Id_Sustancia { get; set; }
    
        public virtual OrdenCompra OrdenCompra { get; set; }
    }
}
