//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DHABIENTES
    {
        public string NUMEMP { get; set; }
        public string CURP { get; set; }
        public string PARIENTE { get; set; }
        public string NOMBRES { get; set; }
        public string APATERNO { get; set; }
        public string AMATERNO { get; set; }
        public Nullable<System.DateTime> FNAC { get; set; }
        public string SEXO { get; set; }
        public Nullable<System.DateTime> FECALTA { get; set; }
        public Nullable<System.DateTime> FVIGENCIA { get; set; }
        public string CVEMED { get; set; }
        public string EMAIL { get; set; }
        public string NUMAFIL { get; set; }
        public string OCUPACION { get; set; }
        public string BAJA { get; set; }
        public Nullable<System.DateTime> FBAJA { get; set; }
        public string DESC_BAJA { get; set; }
        public string ARCHIVO { get; set; }
        public string EMP_REALIZO { get; set; }
        public Nullable<System.DateTime> fec_foto { get; set; }
        public Nullable<System.DateTime> fec_cred { get; set; }
        public string status_rep { get; set; }
        public string protocolo_vac { get; set; }
        public Nullable<System.DateTime> fec_alta_cei { get; set; }
        public Nullable<System.DateTime> fec_ing_cei { get; set; }
        public string salon { get; set; }
        public string num_cei { get; set; }
        public string tel_oficina { get; set; }
        public string tel_casa { get; set; }
        public string tel_celular { get; set; }
        public string fv_registro { get; set; }
        public Nullable<System.DateTime> fv_fecha { get; set; }
        public string fv_nota { get; set; }
        public string fv_ip { get; set; }
        public string FV_NOTA2 { get; set; }
        public string medico { get; set; }
        public string medico_grupo { get; set; }
        public string REGHU { get; set; }
        public string medico_dmhta { get; set; }
        public string mat_uanl { get; set; }
        public string esc_uanl { get; set; }
        public string tipo_asign_med { get; set; }
        public string tel_consulta { get; set; }
        public string foto { get; set; }
        public string credencial_exp { get; set; }
        public Nullable<System.DateTime> fecha_credencial { get; set; }
    }
}
