//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMDEVEntities33 : DbContext
    {
        public SMDEVEntities33()
            : base("name=SMDEVEntities33")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AFILIADOS> AFILIADOS { get; set; }
        public virtual DbSet<DHABIENTES> DHABIENTES { get; set; }
        public virtual DbSet<DEPENDENCIAS> DEPENDENCIAS { get; set; }
        public virtual DbSet<MEDICOS> MEDICOS { get; set; }
        public virtual DbSet<receta_detalle_crn> receta_detalle_crn { get; set; }
        public virtual DbSet<receta_exp_crn> receta_exp_crn { get; set; }
        public virtual DbSet<InventarioFarmacia> InventarioFarmacia { get; set; }
        public virtual DbSet<TIPOSCONSULTA> TIPOSCONSULTA { get; set; }
        public virtual DbSet<Citas_Medicos_Externos> Citas_Medicos_Externos { get; set; }
        public virtual DbSet<expediente> expediente { get; set; }
        public virtual DbSet<Receta_Detalle_2> Receta_Detalle_2 { get; set; }
        public virtual DbSet<RECETA_EXP_2> RECETA_EXP_2 { get; set; }
        public virtual DbSet<ESPECIALIDADES> ESPECIALIDADES { get; set; }
        public virtual DbSet<Sustancia> Sustancia { get; set; }
        public virtual DbSet<Orden_Int> Orden_Int { get; set; }
        public virtual DbSet<Orden_Int_Enviar> Orden_Int_Enviar { get; set; }
        public virtual DbSet<prov_subrrogados> prov_subrrogados { get; set; }
        public virtual DbSet<DIAGNOSTICOS> DIAGNOSTICOS { get; set; }
        public virtual DbSet<Lab_detalle> Lab_detalle { get; set; }
        public virtual DbSet<Lab_exp> Lab_exp { get; set; }
        public virtual DbSet<NotaOperatoria> NotaOperatoria { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Comunicados> Comunicados { get; set; }
        public virtual DbSet<ComunicadoUsuario> ComunicadoUsuario { get; set; }
        public virtual DbSet<NotaFar_Usuario> NotaFar_Usuario { get; set; }
        public virtual DbSet<Alergias_Exp> Alergias_Exp { get; set; }
        public virtual DbSet<TblNotaFarmaco> TblNotaFarmaco { get; set; }
        public virtual DbSet<PruebaAntigenos> PruebaAntigenos { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CovidSolicitud> CovidSolicitud { get; set; }
        public virtual DbSet<TrabajoSocialNota> TrabajoSocialNota { get; set; }
        public virtual DbSet<NotaTS_Usuario> NotaTS_Usuario { get; set; }
        public virtual DbSet<prestaciones_servicios> prestaciones_servicios { get; set; }
        public virtual DbSet<prestaciones_subservicios> prestaciones_subservicios { get; set; }
        public virtual DbSet<proveedor_subservicio> proveedor_subservicio { get; set; }
        public virtual DbSet<SolicitudPrestaciones> SolicitudPrestaciones { get; set; }
        public virtual DbSet<TicketAreas> TicketAreas { get; set; }
        public virtual DbSet<TicketSeguimiento> TicketSeguimiento { get; set; }
        public virtual DbSet<TicketTipo> TicketTipo { get; set; }
        public virtual DbSet<InterconsultasSub> InterconsultasSub { get; set; }
        public virtual DbSet<InterconsultaMedico> InterconsultaMedico { get; set; }
        public virtual DbSet<UnidadMedica> UnidadMedica { get; set; }
        public virtual DbSet<NotaQuirurgica> NotaQuirurgica { get; set; }
        public virtual DbSet<AltaUrgencias> AltaUrgencias { get; set; }
        public virtual DbSet<MedicoMedicamento> MedicoMedicamento { get; set; }
        public virtual DbSet<receta_detalle_crn_edit> receta_detalle_crn_edit { get; set; }
        public virtual DbSet<Insumos> Insumos { get; set; }
    }
}
