//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAGNOSTICOS
    {
        public string Clave { get; set; }
        public string DesCorta { get; set; }
        public string DescCompleta { get; set; }
        public string Grupo { get; set; }
        public string Especialidad { get; set; }
        public string Estatus { get; set; }
        public string clave2 { get; set; }
        public string dental { get; set; }
        public string estatus_exp { get; set; }
    }
}
