//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directorio
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Usuario { get; set; }
        public string Departamento { get; set; }
        public string Ubicacion { get; set; }
        public string Puesto { get; set; }
        public string NombreEquipo { get; set; }
        public string IP { get; set; }
        public string Tipo { get; set; }
        public string MarcaCPU { get; set; }
        public string ModeloCPU { get; set; }
        public string SerieCPU { get; set; }
        public string MarcaMonitor { get; set; }
        public string ModeloMonitor { get; set; }
        public string SerieMonitor { get; set; }
        public string Office { get; set; }
        public string ModeloImpresora { get; set; }
        public string SerieImpresora { get; set; }
        public string ConexionImpresora { get; set; }
        public string ModeloTelefono { get; set; }
        public string SerieTelefono { get; set; }
        public string NumDirecto { get; set; }
        public Nullable<int> Extension { get; set; }
        public string Display { get; set; }
    }
}
