//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class encuesta_covid
    {
        public string expediente { get; set; }
        public string medico { get; set; }
        public string veces_consulta { get; set; }
        public string aislamiento { get; set; }
        public string dif_respirar { get; set; }
        public string int_requerido { get; set; }
        public string oxi_requerido { get; set; }
        public string vent_asistida { get; set; }
        public string alta { get; set; }
        public string fam_sintomas { get; set; }
        public string derechohabiente { get; set; }
        public Nullable<System.DateTime> inc_vence { get; set; }
        public string comentarios { get; set; }
        public Nullable<System.DateTime> fecha_enc { get; set; }
        public Nullable<System.DateTime> fecha_pos { get; set; }
        public Nullable<decimal> dias_prueba { get; set; }
        public string gpo_riesgo { get; set; }
        public string trabajo_ubica { get; set; }
    }
}
