//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class encuesta_covid_segunda
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> edad { get; set; }
        public string expediente { get; set; }
        public string antecedentes_medicos { get; set; }
        public Nullable<int> fiebre { get; set; }
        public Nullable<int> tos { get; set; }
        public Nullable<int> anosmia { get; set; }
        public Nullable<int> diarrea { get; set; }
        public Nullable<int> mialgias_atralgias { get; set; }
        public Nullable<int> hta_cardivascular { get; set; }
        public Nullable<int> diabetes_mellitus { get; set; }
        public Nullable<int> tabaquismo { get; set; }
        public Nullable<int> enf_inmunologica { get; set; }
        public Nullable<int> enf_reumatologia { get; set; }
        public Nullable<int> enf_neoplasica { get; set; }
        public Nullable<int> irc { get; set; }
        public Nullable<int> edad_mayo { get; set; }
        public Nullable<int> fr { get; set; }
        public Nullable<int> disnea { get; set; }
        public Nullable<int> saturacion_oxigeno { get; set; }
        public Nullable<int> hipotension { get; set; }
        public Nullable<int> alteracion_estado { get; set; }
        public Nullable<int> alteracion_pulmonares { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string notas { get; set; }
    }
}
