//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnfermeriaSolicitud
    {
        public int SolicitudId { get; set; }
        public string NumEmp { get; set; }
        public string Medico { get; set; }
        public string Nota { get; set; }
        public System.DateTime FechaSol { get; set; }
        public System.DateTime FechaAgenda { get; set; }
        public string UsuarioAgenda { get; set; }
        public string UsuarioRealiza { get; set; }
        public System.DateTime FechaRealiza { get; set; }
        public string NotaRealiza { get; set; }
        public bool Finalizado { get; set; }
        public string Urgente { get; set; }
        public bool Cancelado { get; set; }
        public bool NoPresento { get; set; }
    }
}
