//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnfermeriaSignosVitales
    {
        public int Id { get; set; }
        public string numemp { get; set; }
        public Nullable<float> peso_r { get; set; }
        public Nullable<float> talla_r { get; set; }
        public Nullable<float> temp_r { get; set; }
        public string fresp { get; set; }
        public string fcard { get; set; }
        public string ta1 { get; set; }
        public string ta2 { get; set; }
        public string dstx { get; set; }
        public string sp2 { get; set; }
        public string UsuarioCaptura { get; set; }
        public System.DateTime FechaCaptura { get; set; }
    }
}
