//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMDEVEnfermeriaSolicitud : DbContext
    {
        public SMDEVEnfermeriaSolicitud()
            : base("name=SMDEVEnfermeriaSolicitud")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EnfermeriaSolicitud> EnfermeriaSolicitud { get; set; }
        public virtual DbSet<EnfermeriaSolicitudDetalle> EnfermeriaSolicitudDetalle { get; set; }
        public virtual DbSet<MEDICOS> MEDICOS { get; set; }
        public virtual DbSet<ServicioEnfermeria> ServicioEnfermeria { get; set; }
    }
}
