//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnfermeriaInventario
    {
        public short CodProducto { get; set; }
        public string Descripcion { get; set; }
        public bool Status { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Entradas { get; set; }
        public Nullable<int> Salidas { get; set; }
        public Nullable<int> Stock { get; set; }
    }
}
