//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnfermeriaSolicitudDetalle
    {
        public int IdDetalle { get; set; }
        public int SolicitudId { get; set; }
        public int IdServicio { get; set; }
        public System.DateTime FechaSol { get; set; }
        public System.DateTime FechaRealiza { get; set; }
        public string UsuarioRealiza { get; set; }
        public string Descripcion { get; set; }
    }
}
