//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPECIALIDADES
    {
        public string CLAVE { get; set; }
        public string DESCRIPCION { get; set; }
        public string OBS_MED { get; set; }
        public string GRUPO_DIR { get; set; }
        public Nullable<decimal> FMSR { get; set; }
        public Nullable<decimal> FMSB { get; set; }
        public Nullable<decimal> FVSR { get; set; }
        public Nullable<decimal> FVSB { get; set; }
        public string TIPO { get; set; }
        public int id_pre_esp { get; set; }
        public string titulo { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> PorcentajePresenciales { get; set; }
        public Nullable<decimal> PorcentajeTelefonicas { get; set; }
    }
}
