//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudioMedicoSocial
    {
        public int EstudioId { get; set; }
        public string Empleado { get; set; }
        public string CveFam { get; set; }
        public string Depcia { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Nombre { get; set; }
        public string Edad { get; set; }
        public string Sexo { get; set; }
        public string EdoCivil { get; set; }
        public string Domicilio { get; set; }
        public string Col { get; set; }
        public string Municipio { get; set; }
        public string Tel { get; set; }
        public string Escolaridad { get; set; }
        public string Ocupacion { get; set; }
        public string Religion { get; set; }
        public string ViveCon { get; set; }
        public string CuidadorPrincipal { get; set; }
        public string TipoFamilia { get; set; }
        public string FaseFamilia { get; set; }
        public Nullable<bool> Eutimia { get; set; }
        public Nullable<bool> Hipertimia { get; set; }
        public Nullable<bool> Distimia { get; set; }
        public string DiagnosticoMedicoIngreso { get; set; }
        public string MedicoAtiende { get; set; }
        public Nullable<int> FrecuenciaAcude { get; set; }
        public string MedicoEspecialidadAcude { get; set; }
        public Nullable<bool> Quemaduras { get; set; }
        public Nullable<bool> Infarto { get; set; }
        public Nullable<bool> Accidentes { get; set; }
        public Nullable<bool> Derrames { get; set; }
        public Nullable<bool> Cancer { get; set; }
        public Nullable<bool> Traumatismo { get; set; }
        public Nullable<bool> Embolia { get; set; }
        public Nullable<bool> Ninguna { get; set; }
        public Nullable<bool> InsuficienciaRenal { get; set; }
        public Nullable<bool> Diabetes { get; set; }
        public Nullable<bool> Hipertension { get; set; }
        public Nullable<bool> EnfermedadesCardiacas { get; set; }
        public Nullable<bool> FiebreRemautica { get; set; }
        public Nullable<bool> ArtritisDegenerativa { get; set; }
        public Nullable<bool> TumoresCerebrales { get; set; }
        public Nullable<bool> MalformacionesCongenitas { get; set; }
        public Nullable<bool> PxTransplantado { get; set; }
        public Nullable<bool> FibrosisQuistica { get; set; }
        public Nullable<bool> LupusEritematoso { get; set; }
        public Nullable<bool> EsclerosisLateral { get; set; }
        public Nullable<bool> EsclerosisMultiple { get; set; }
        public Nullable<bool> Hidrocefalia { get; set; }
        public Nullable<bool> EspinaBifida { get; set; }
        public Nullable<bool> IntervencionCrisisPaciente { get; set; }
        public Nullable<bool> CasoSocial { get; set; }
        public Nullable<bool> ConsultaAsesoria { get; set; }
        public Nullable<bool> VisitaDomiciliaria { get; set; }
        public Nullable<bool> IntervencionFamiliar { get; set; }
        public Nullable<bool> CanalizacionPsicologica { get; set; }
        public Nullable<bool> OrientacionTramitesAdmin { get; set; }
        public Nullable<bool> CanalizacionOtraInstitucion { get; set; }
        public string OtraIntervencionTipo { get; set; }
        public string ValoracionPsicoSocial { get; set; }
        public string Diagnostico { get; set; }
        public string EstrategiaTrabajo { get; set; }
        public string ResumenCaso { get; set; }
        public string Observaciones { get; set; }
    }
}
