//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expediente
    {
        public string numemp { get; set; }
        public string pariente { get; set; }
        public string curp { get; set; }
        public string medico { get; set; }
        public System.DateTime fecha { get; set; }
        public string diagnostico { get; set; }
        public string diagnostico2 { get; set; }
        public string diagnostico3 { get; set; }
        public string s_exp { get; set; }
        public string o_exp { get; set; }
        public string a_exp { get; set; }
        public string p_exp { get; set; }
        public string pesokg { get; set; }
        public string pesomg { get; set; }
        public string tallam { get; set; }
        public string tallac { get; set; }
        public string ta1 { get; set; }
        public string ta2 { get; set; }
        public string tipconsulta { get; set; }
        public string emprealizo { get; set; }
        public Nullable<System.DateTime> frealizo { get; set; }
        public string turno { get; set; }
        public string referido { get; set; }
        public string referido_urg { get; set; }
        public string incapacidad { get; set; }
        public string laboratorio { get; set; }
        public string receta { get; set; }
        public string edd_anio { get; set; }
        public string edd_mes { get; set; }
        public string MED_TMP { get; set; }
        public string ref_exp { get; set; }
        public string c_ref_exp { get; set; }
        public string ref_stat { get; set; }
        public Nullable<float> talla_r { get; internal set; }
        public Nullable<float> peso_r { get; set; }
        public Nullable<float> temp_r { get; set; }
        public string fresp { get; set; }
        public string fcard { get; set; }
        public string rxd { get; set; }
        public string dstx { get; set; }
        public Nullable<System.DateTime> hora_termino { get; set; }
        public string tipconsulta2 { get; set; }
        public string tipconsulta3 { get; set; }
        public string consultadistancia { get; set; }
        public Nullable<decimal> ubicacion_realiza { get; set; }
        public string ip_realiza { get; set; }
        public string referido2 { get; set; }
        public string referido_urg2 { get; set; }
        public string ref_exp2 { get; set; }
        public string referido3 { get; set; }
        public string referido_urg3 { get; set; }
        public string ref_exp3 { get; set; }
        public string proxima_cita { get; set; }
        public Nullable<System.DateTime> fecha_prox_cita { get; set; }
        public string per_cefalico { get; set; }
        public string masa_muscular { get; set; }
        public string masa_grasa { get; set; }
        public string porcentaje_grasa { get; set; }
        public Nullable<int> subreferido { get; set; }
        public string medicoreferido { get; set; }
        public Nullable<int> subreferido2 { get; set; }
        public string medicoreferido2 { get; set; }
        public Nullable<int> subreferido3 { get; set; }
        public string medicoreferido3 { get; set; }
    }
}
