//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class incidentesEntities3 : DbContext
    {
        public incidentesEntities3()
            : base("name=incidentesEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<INVENTARIO> INVENTARIO { get; set; }
        public virtual DbSet<sis_areas> sis_areas { get; set; }
        public virtual DbSet<sis_estado> sis_estado { get; set; }
        public virtual DbSet<sis_marcas> sis_marcas { get; set; }
        public virtual DbSet<sis_modcpu> sis_modcpu { get; set; }
        public virtual DbSet<tipo_incidente> tipo_incidente { get; set; }
        public virtual DbSet<INV_GRAL> INV_GRAL { get; set; }
        public virtual DbSet<SOL_SERVICIO> SOL_SERVICIO { get; set; }
    }
}
