//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterconsultaMedico
    {
        public int id { get; set; }
        public Nullable<int> id_subcategoria { get; set; }
        public string medico { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> imprimir { get; set; }
    }
}
