//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_GRAL
    {
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string CPU_MODELO { get; set; }
        public string CPU_MARCA { get; set; }
        public string CPU_SERIE { get; set; }
        public string MONITOR_MODELO { get; set; }
        public string MONITOR_MARCA { get; set; }
        public string MONITOR_SERIE { get; set; }
        public string TECLADO_MODELO { get; set; }
        public string TECLADO_MARCA { get; set; }
        public string TECLADO_SERIE { get; set; }
        public string MOUSE_MODELO { get; set; }
        public string MOUSE_MARCA { get; set; }
        public string MOUSE_SERIE { get; set; }
        public string DIRECCION_IP { get; set; }
        public string ESTATUS { get; set; }
        public string OBS { get; set; }
        public string RACK { get; set; }
        public string INV_COD { get; set; }
    }
}
