//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvAlmFarm
    {
        public int Id { get; set; }
        public short InvAlmId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id_Sustancia { get; set; }
        public int Inv_Ini { get; set; }
        public int Inv_Ent { get; set; }
        public int Inv_Sal { get; set; }
        public int Inv_Disp { get; set; }
        public int Inv_Reorden { get; set; }
        public Nullable<int> ManejoDisponible { get; set; }
        public string Usuario_Registra { get; set; }
    
        public virtual Inventario_1 Inventario { get; set; }
    }
}
