//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTARIO()
        {
            this.SOL_SERVICIO = new HashSet<SOL_SERVICIO>();
        }
    
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string CPU_MODELO { get; set; }
        public string CPU_MARCA { get; set; }
        public string CPU_SERIE { get; set; }
        public string MONITOR_MODELO { get; set; }
        public string MONITOR_MARCA { get; set; }
        public string MONITOR_SERIE { get; set; }
        public string TECLADO_MODELO { get; set; }
        public string TECLADO_MARCA { get; set; }
        public string TECLADO_SERIE { get; set; }
        public string MOUSE_MODELO { get; set; }
        public string MOUSE_MARCA { get; set; }
        public string MOUSE_SERIE { get; set; }
        public string DIRECCION_IP { get; set; }
        public string ESTATUS { get; set; }
        public string OBS { get; set; }
        public string RACK { get; set; }
        public string INV_COD { get; set; }
        public string num_cons { get; set; }
        public string recepcion_mt { get; set; }
    
        public virtual sis_estado sis_estado { get; set; }
        public virtual sis_marcas sis_marcas { get; set; }
        public virtual sis_marcas sis_marcas1 { get; set; }
        public virtual sis_marcas sis_marcas2 { get; set; }
        public virtual sis_marcas sis_marcas3 { get; set; }
        public virtual sis_modcpu sis_modcpu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOL_SERVICIO> SOL_SERVICIO { get; set; }
    }
}
