//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SERVMEDInventario : DbContext
    {
        public SERVMEDInventario()
            : base("name=SERVMEDInventario")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CodigoBarras> CodigoBarras { get; set; }
        public virtual DbSet<Detalle_VE> Detalle_VE { get; set; }
        public virtual DbSet<DetalleOC> DetalleOC { get; set; }
        public virtual DbSet<DetalleReq> DetalleReq { get; set; }
        public virtual DbSet<OrdenCompra> OrdenCompra { get; set; }
        public virtual DbSet<Requisicion> Requisicion { get; set; }
        public virtual DbSet<ValeEntrada> ValeEntrada { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
    }
}
