//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab_detalle
    {
        public int Folio_lab { get; set; }
        public decimal id_indicaciones { get; set; }
        public string id_servicio { get; set; }
        public string id_lab { get; set; }
    }
}
