//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsn_time_mapping
    {
        public byte[] start_lsn { get; set; }
        public Nullable<System.DateTime> tran_begin_time { get; set; }
        public Nullable<System.DateTime> tran_end_time { get; set; }
        public byte[] tran_id { get; set; }
        public byte[] tran_begin_lsn { get; set; }
    }
}
