//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICOS
    {
        public string Estatus { get; set; }
        public string Numero { get; set; }
        public string Apaterno { get; set; }
        public string Amaterno { get; set; }
        public string Nombre { get; set; }
        public string Titulo { get; set; }
        public string Consultorio { get; set; }
        public Nullable<System.DateTime> FCancelini { get; set; }
        public Nullable<System.DateTime> FCancelFin { get; set; }
        public string ObsCancel { get; set; }
        public string Recepcion { get; set; }
        public string Cedula { get; set; }
        public string HrLunes { get; set; }
        public string ObLunes { get; set; }
        public string pac_lun { get; set; }
        public string hrlun { get; set; }
        public string HrMartes { get; set; }
        public string ObMartes { get; set; }
        public string pac_mar { get; set; }
        public string hrmar { get; set; }
        public string HrMiercoles { get; set; }
        public string ObMiercoles { get; set; }
        public string pac_mie { get; set; }
        public string hrmie { get; set; }
        public string HrJueves { get; set; }
        public string ObJueves { get; set; }
        public string pac_jue { get; set; }
        public string hrjue { get; set; }
        public string HrViernes { get; set; }
        public string ObViernes { get; set; }
        public string pac_vie { get; set; }
        public string hrvie { get; set; }
        public string HrSabado { get; set; }
        public string ObSabado { get; set; }
        public string pac_sab { get; set; }
        public string hrsab { get; set; }
        public string HrDomingo { get; set; }
        public string ObDomingo { get; set; }
        public string pac_dom { get; set; }
        public string hrdom { get; set; }
        public string Socio1 { get; set; }
        public string Socio2 { get; set; }
        public Nullable<System.DateTime> FCubreIni { get; set; }
        public Nullable<System.DateTime> FCubreFin { get; set; }
        public string CubreMed { get; set; }
        public Nullable<System.DateTime> hora { get; set; }
        public Nullable<int> bloqueado { get; set; }
        public string cveesp { get; set; }
        public Nullable<System.DateTime> fechab { get; set; }
        public string USUARIO { get; set; }
        public string CLAVE { get; set; }
        public string TIP_HORARIO { get; set; }
        public string Estatus_Lab { get; set; }
        public string GRUPO_DIR { get; set; }
        public Nullable<System.DateTime> f2cancelini { get; set; }
        public Nullable<System.DateTime> f2cancelfin { get; set; }
        public string obs2cancel { get; set; }
        public string medico_grupo { get; set; }
        public Nullable<int> accesoweb { get; set; }
        public string consultorio_mt { get; set; }
        public string sexo { get; set; }
        public string cve_uni { get; set; }
        public string cedula_esp { get; set; }
        public string temporal { get; set; }
        public Nullable<int> emp_numemp { get; set; }
        public Nullable<decimal> unidad_medica { get; set; }
        public Nullable<decimal> exap_max { get; set; }
    }
}
