//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSreplication_queue
    {
        public string publisher { get; set; }
        public string publisher_db { get; set; }
        public string publication { get; set; }
        public string tranid { get; set; }
        public byte[] data { get; set; }
        public Nullable<int> datalen { get; set; }
        public Nullable<int> commandtype { get; set; }
        public Nullable<System.DateTime> insertdate { get; set; }
        public long orderkey { get; set; }
        public bool cmdstate { get; set; }
    }
}
