//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSsubscription_articles
    {
        public int agent_id { get; set; }
        public int artid { get; set; }
        public string article { get; set; }
        public string dest_table { get; set; }
        public string owner { get; set; }
        public string cft_table { get; set; }
    }
}
