//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SMDEVEntities38 : DbContext
    {
        public SMDEVEntities38()
            : base("name=SMDEVEntities38")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblNotaFarmaco> TblNotaFarmaco { get; set; }
    
        public virtual ObjectResult<Sp_NotasFarmaco_Result> Sp_NotasFarmaco(string numEmp)
        {
            var numEmpParameter = numEmp != null ?
                new ObjectParameter("NumEmp", numEmp) :
                new ObjectParameter("NumEmp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_NotasFarmaco_Result>("Sp_NotasFarmaco", numEmpParameter);
        }
    }
}
