//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaIngreso
    {
        public int IngresoId { get; set; }
        public string Medico { get; set; }
        public string NumEmp { get; set; }
        public System.DateTime Fecha { get; set; }
        public string T { get; set; }
        public string A { get; set; }
        public int Pulso { get; set; }
        public int Respiracion { get; set; }
        public decimal Temp { get; set; }
        public string MotivoIngreso { get; set; }
        public string ResumenInterrogatorio { get; set; }
        public string ResLabGabinete { get; set; }
        public string DiagnosticoPresuntivo { get; set; }
        public string PlanManejo { get; set; }
        public string Pronostico { get; set; }
        public string DiagnosticoDesc { get; set; }
        public Nullable<int> OrdenFolio { get; set; }
        public string UsuarioCreacion { get; set; }
    }
}
