//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaPreoperatoria
    {
        public int PreOperatoriaId { get; set; }
        public int OrdenFolio { get; set; }
        public string Medico { get; set; }
        public string NumEmp { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Diagnostico { get; set; }
        public string DiagnosticoDesc { get; set; }
        public string PlanesCuidados { get; set; }
        public string PlanQuirurgico { get; set; }
        public string FactoresRiesgo { get; set; }
        public string RiesgoQuirurgico { get; set; }
        public string Pronostico { get; set; }
        public string UsuarioCreacion { get; set; }
        public int IngresoId { get; set; }
    }
}
