//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaQuirurgica
    {
        public int id { get; set; }
        public Nullable<int> id_orden { get; set; }
        public string cirugia_planeada { get; set; }
        public string cirugia_realizada { get; set; }
        public string tipo_anestesia { get; set; }
        public string descripcion { get; set; }
        public string hallazgo { get; set; }
        public string incidentes { get; set; }
        public string sangrado { get; set; }
        public string motivo_egreso { get; set; }
        public string estado_actual { get; set; }
        public string plan_manejo { get; set; }
        public string pronostico { get; set; }
        public Nullable<int> tiempo { get; set; }
        public string diagnostico1 { get; set; }
        public string diagnostico2 { get; set; }
        public string diagnostico3 { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string ip_realiza { get; set; }
    }
}
