//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaEgreso
    {
        public int EgresoId { get; set; }
        public int OrdenFolio { get; set; }
        public string Medico { get; set; }
        public string NumEmp { get; set; }
        public string DiagnosticoFinal { get; set; }
        public string DiagnosticoDesc { get; set; }
        public string ResumenClinico { get; set; }
        public string ProcedimientoRealizado { get; set; }
        public string ProcProblemasPendientes { get; set; }
        public string Medicacion { get; set; }
        public string RecomendacionesIncapacidad { get; set; }
        public string Pronostico { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int OperatoriaId { get; set; }
    }
}
