//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaOperatoria
    {
        public int OperatoriaId { get; set; }
        public int OrdenFolio { get; set; }
        public Nullable<int> PreOperatoriaId { get; set; }
        public string Medico { get; set; }
        public string NumEmp { get; set; }
        public string ResumenClinico { get; set; }
        public string ResEstudiosDiagnosticos { get; set; }
        public string DiagnosticoIngreso { get; set; }
        public string DiagnosticoIngresoDesc { get; set; }
        public string PlanTerCirujiaPlaneada { get; set; }
        public string RiesgoQuirurgico { get; set; }
        public string CirujiaRealizada { get; set; }
        public string DiagnosticoEgreso { get; set; }
        public string DiagnosticoEgresoDesc { get; set; }
        public string TipoAnestecia { get; set; }
        public string DescTecnicaQuirurgicaTerapeutica { get; set; }
        public string Hallazgos { get; set; }
        public string Incidentes { get; set; }
        public string Sangrado { get; set; }
        public Nullable<int> MotivoEgreso { get; set; }
        public string EstadoActualProblemasClinicos { get; set; }
        public string PlanManejo { get; set; }
        public string Pronostico { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
