//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUEVOLEON
    {
        public string clave_col { get; set; }
        public Nullable<double> d_codigo { get; set; }
        public string d_asenta { get; set; }
        public string d_tipo_asenta { get; set; }
        public string d_mnpio { get; set; }
        public string d_estado { get; set; }
        public string d_ciudad { get; set; }
        public Nullable<double> d_CP { get; set; }
        public Nullable<double> c_estado { get; set; }
        public Nullable<double> c_oficina { get; set; }
        public Nullable<double> c_CP { get; set; }
        public Nullable<double> c_tipo_asenta { get; set; }
        public Nullable<double> c_mnpio { get; set; }
        public string clave_unidad { get; set; }
    }
}
