//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_Int
    {
        public int id_orden { get; set; }
        public string numemp { get; set; }
        public string medico { get; set; }
        public Nullable<System.DateTime> fecha_internamiento { get; set; }
        public string proveedor { get; set; }
        public string estudios { get; set; }
        public string motivo { get; set; }
        public string indicaciones { get; set; }
        public string diagnostico1 { get; set; }
        public string diagnostico2 { get; set; }
        public string diagnostico3 { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string folio { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<int> estatus { get; set; }
        public string comentarios { get; set; }
        public Nullable<int> tipo { get; set; }
        public string resumen_medico { get; set; }
        public Nullable<int> enviar_a { get; set; }
        public Nullable<int> nota_quirurgica { get; set; }
        public string motivo_alta { get; set; }
    }
}
