//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prov_subrrogados
    {
        public string clave { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string colonia { get; set; }
        public string ciudad { get; set; }
        public string horario { get; set; }
        public string observaciones { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string estado { get; set; }
        public int id_pre_prov { get; set; }
        public Nullable<int> adomicilio { get; set; }
        public string obs { get; set; }
        public string maps { get; set; }
        public string croquis { get; set; }
    }
}
