//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class receta_exp_crn
    {
        public int folio_rc { get; set; }
        public string medico_crea { get; set; }
        public string medico_ref { get; set; }
        public System.DateTime fecha_crea { get; set; }
        public int estado { get; set; }
        public int platica_edu { get; set; }
        public string lab_relev { get; set; }
        public string trat_actual { get; set; }
        public System.DateTime fec_ini_sintomas { get; set; }
        public string evento_adverso { get; set; }
        public int meses_surtir { get; set; }
        public string expediente { get; set; }
        public int policl { get; set; }
        public string px_special { get; set; }
        public Nullable<int> terminada { get; set; }
        public string proxima_cita { get; set; }
        public Nullable<float> costo { get; set; }
        public Nullable<System.DateTime> fecha_kiosco { get; set; }
        public Nullable<int> turnofar { get; set; }
        public Nullable<System.DateTime> fecha_prox_cita { get; set; }
        public Nullable<int> editada { get; set; }
    }
}
