//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class receta_detalle_crn_edit
    {
        public int id { get; set; }
        public Nullable<int> folio_rc { get; set; }
        public string codigo { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string dosis { get; set; }
        public string indicaciones { get; set; }
        public Nullable<float> costo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string ip_realiza { get; set; }
        public string usuario_realiza { get; set; }
    }
}
