//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteActividadesSemanal
    {
        public int ReporteSemanalActividadId { get; set; }
        public int ActividadId { get; set; }
        public int Cantidad { get; set; }
        public int Semana { get; set; }
        public int CantidadSemanaPasada { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string UsuarioRealiza { get; set; }
        public System.DateTime FechaRealiza { get; set; }
    }
}
