//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SERVMEDEntities8 : DbContext
    {
        public SERVMEDEntities8()
            : base("name=SERVMEDEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cotizaciones> Cotizaciones { get; set; }
        public virtual DbSet<DetalleReq> DetalleReq { get; set; }
        public virtual DbSet<Requisicion_1> Requisicion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<DetalleOC> DetalleOC { get; set; }
        public virtual DbSet<OrdenCompra> OrdenCompra { get; set; }
    }
}
