//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisicion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisicion()
        {
            this.DetalleReq = new HashSet<DetalleReq>();
            this.ValeEntrada = new HashSet<ValeEntrada>();
        }
    
        public int id { get; set; }
        public string clave { get; set; }
        public byte Id_Tipo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public bool cerrado { get; set; }
        public string UserId { get; set; }
        public string EstatusContrato { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleReq> DetalleReq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValeEntrada> ValeEntrada { get; set; }
    }
}
