//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal
    {
        public short Id { get; set; }
        public short Id_Grupo { get; set; }
        public string Clave_Sal { get; set; }
        public string Descripcion_Sal { get; set; }
        public bool Status_Sal { get; set; }
    }
}
