//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISM_MOV_INV
    {
        public int Id_Mov_Inv { get; set; }
        public Nullable<int> Id_Sustancia { get; set; }
        public Nullable<int> C_Anterior { get; set; }
        public Nullable<int> C_Actual { get; set; }
        public Nullable<int> Tipo_Mov { get; set; }
        public Nullable<System.DateTime> Fecha_Mov { get; set; }
        public string Id_User { get; set; }
        public string IP_User { get; set; }
    }
}
