//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISM_INV_MED
    {
        public int Id_Inv { get; set; }
        public Nullable<int> Id_Sustancia { get; set; }
        public Nullable<int> C_Inicio { get; set; }
        public Nullable<int> C_Entrada { get; set; }
        public Nullable<int> C_Salida { get; set; }
        public Nullable<int> C_Actual { get; set; }
    }
}
