//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISM_VALE_ENTRADA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SISM_VALE_ENTRADA()
        {
            this.SISM_DET_VALE_ENTRADA = new HashSet<SISM_DET_VALE_ENTRADA>();
        }
    
        public int Id_ValeEntrada { get; set; }
        public string Clave { get; set; }
        public Nullable<int> Id_OrdenCompra { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Id_User { get; set; }
        public string IP_User { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SISM_DET_VALE_ENTRADA> SISM_DET_VALE_ENTRADA { get; set; }
    }
}
