//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SERVMEDEntities5 : DbContext
    {
        public SERVMEDEntities5()
            : base("name=SERVMEDEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cantidadenvases_21> cantidadenvases_21 { get; set; }
        public virtual DbSet<CodigoBarras> CodigoBarras { get; set; }
        public virtual DbSet<concentracion_21> concentracion_21 { get; set; }
        public virtual DbSet<formafarm_21> formafarm_21 { get; set; }
        public virtual DbSet<grupo_21> grupo_21 { get; set; }
        public virtual DbSet<nivel_21> nivel_21 { get; set; }
        public virtual DbSet<principioactivo_21> principioactivo_21 { get; set; }
        public virtual DbSet<tipodeenvase_21> tipodeenvase_21 { get; set; }
        public virtual DbSet<unidadeslicitacion_21> unidadeslicitacion_21 { get; set; }
        public virtual DbSet<unidadesmedida_21> unidadesmedida_21 { get; set; }
        public virtual DbSet<Sustancia> Sustancia { get; set; }
    
        public virtual ObjectResult<Sp_GetInfInv_Result> Sp_GetInfInv()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetInfInv_Result>("Sp_GetInfInv");
        }
    
        public virtual ObjectResult<SP_MedNuevos_Result> SP_MedNuevos(string clave, string nomComercial, string codigoBar)
        {
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            var nomComercialParameter = nomComercial != null ?
                new ObjectParameter("NomComercial", nomComercial) :
                new ObjectParameter("NomComercial", typeof(string));
    
            var codigoBarParameter = codigoBar != null ?
                new ObjectParameter("CodigoBar", codigoBar) :
                new ObjectParameter("CodigoBar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MedNuevos_Result>("SP_MedNuevos", claveParameter, nomComercialParameter, codigoBarParameter);
        }
    
        public virtual int Sp_ReporteAbastecimiento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_ReporteAbastecimiento");
        }
    
        public virtual int Sp_ReporteConsumoAnual(Nullable<int> año)
        {
            var añoParameter = año.HasValue ?
                new ObjectParameter("Año", año) :
                new ObjectParameter("Año", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_ReporteConsumoAnual", añoParameter);
        }
    
        public virtual int Sp_ReporteConsumoFarm()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_ReporteConsumoFarm");
        }
    
        public virtual ObjectResult<SP_ViewCodBar2022_Result> SP_ViewCodBar2022()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ViewCodBar2022_Result>("SP_ViewCodBar2022");
        }
    
        public virtual ObjectResult<Sp_GetInfInv1_Result> Sp_GetInfInv1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetInfInv1_Result>("Sp_GetInfInv1");
        }
    
        public virtual ObjectResult<Sp_GetListaMed_Result> Sp_GetListaMed()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetListaMed_Result>("Sp_GetListaMed");
        }
    }
}
