//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISM_DETALLE_REQ_FARMACIA
    {
        public int Id_Detalle_ReqFarm { get; set; }
        public Nullable<int> Id_Sustancia { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Clave { get; set; }
        public string Descripcion { get; set; }
        public string Compendio { get; set; }
        public int Id_Requisicion_Farm { get; set; }
    
        public virtual SISM_REQUISICION_FARMACIA SISM_REQUISICION_FARMACIA { get; set; }
    }
}
