//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblDetalleOrdenCompra> TblDetalleOrdenCompra { get; set; }
        public virtual DbSet<TblDetalleRequisicion> TblDetalleRequisicion { get; set; }
        public virtual DbSet<TblOrdenCompra> TblOrdenCompra { get; set; }
        public virtual DbSet<TblRequisicion> TblRequisicion { get; set; }
    
        public virtual ObjectResult<Sp_DetalleRequisiciones_Result> Sp_DetalleRequisiciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_DetalleRequisiciones_Result>("Sp_DetalleRequisiciones");
        }
    
        public virtual ObjectResult<Sp_Requisiciones_Result> Sp_Requisiciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Requisiciones_Result>("Sp_Requisiciones");
        }
    }
}
