//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISM_CODIGOBARRAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SISM_CODIGOBARRAS()
        {
            this.SISM_DET_VALE_ENTRADA = new HashSet<SISM_DET_VALE_ENTRADA>();
        }
    
        public int Id_CodigoBarras { get; set; }
        public string CodigoBarras { get; set; }
        public Nullable<int> Id_Sustancia { get; set; }
        public string Laboratorio { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<decimal> CostoAnterior { get; set; }
        public Nullable<decimal> CostoActual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SISM_DET_VALE_ENTRADA> SISM_DET_VALE_ENTRADA { get; set; }
    }
}
