//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISM_DET_VALE_ENTRADA
    {
        public int Id_Detalle_VE { get; set; }
        public int Id_ValeEntrada { get; set; }
        public Nullable<int> Id_Sustancia { get; set; }
        public Nullable<int> C_Entrada { get; set; }
        public int Id_CodigoBarras { get; set; }
        public Nullable<decimal> Costo { get; set; }
    
        public virtual SISM_CODIGOBARRAS SISM_CODIGOBARRAS { get; set; }
        public virtual SISM_VALE_ENTRADA SISM_VALE_ENTRADA { get; set; }
    }
}
