//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOL_SERVICIO
    {
        public string TIPO_SOL { get; set; }
        public string EMP_SOL { get; set; }
        public Nullable<System.DateTime> FECHA_SOL { get; set; }
        public string AREA_SOL { get; set; }
        public string EQUIPO_SOL { get; set; }
        public string DESC_SOL { get; set; }
        public string CALIF_SOL { get; set; }
        public string EMP_SIS { get; set; }
        public string DX_SIS { get; set; }
        public string SOL_SIS { get; set; }
        public Nullable<System.DateTime> FEC_SIS { get; set; }
        public string emp_atiende { get; set; }
        public string emp_soluciona { get; set; }
        public decimal folio { get; set; }
        public string prg_sol { get; set; }
        public string req_sol { get; set; }
        public string emp_asignado { get; set; }
        public string seguimiento { get; set; }
        public string seguimiento_cliente { get; set; }
        public string proyecto_largoplazo { get; set; }
        public Nullable<System.DateTime> fecha_incidente { get; set; }
        public Nullable<System.DateTime> fecha_seguimiento { get; set; }
        public Nullable<decimal> fuente_recepcion { get; set; }
        public Nullable<decimal> tipo_incidente { get; set; }
        public string expediente { get; set; }
        public string parentesco { get; set; }
        public Nullable<decimal> naturaleza_incidente { get; set; }
        public string tipo_contrato { get; set; }
        public string persona_reporta { get; set; }
        public string dep_incidente { get; set; }
        public string prov_incidente { get; set; }
        public Nullable<decimal> area_incidente { get; set; }
        public Nullable<decimal> emp_incidente { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public Nullable<decimal> tipo_solucion { get; set; }
        public string seguimiento_jefe { get; set; }
        public Nullable<System.DateTime> fecha_seg_jefe { get; set; }
        public Nullable<int> jefe_asignado { get; set; }
        public Nullable<decimal> area_reasignada { get; set; }
        public string coord_notifica { get; set; }
        public Nullable<System.DateTime> fecha_coord_notifica { get; set; }
    
        public virtual INVENTARIO INVENTARIO { get; set; }
        public virtual sis_areas sis_areas { get; set; }
    }
}
