//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudLab
    {
        public int Solicitud_Id { get; set; }
        public string Paciente_Id { get; set; }
        public string Paciente_Nombre { get; set; }
        public string Paciente_Apellido_Paterno { get; set; }
        public string Paciente_Apellido_Materno { get; set; }
        public int Paciente_Sexo { get; set; }
        public System.DateTime Paciente_Fecha_Nacimiento { get; set; }
        public string Paciente_Telefono { get; set; }
        public string Paciente_Correo { get; set; }
        public string Paciente_Dependencia_Id { get; set; }
        public string Paciente_Dependencia_Descripcion { get; set; }
        public string Solicitud_Expediente { get; set; }
        public string Solicitud_Medico_Id { get; set; }
        public string Solicitud_Medico_Nombre { get; set; }
        public string Solicitud_Diagnostico1_Id { get; set; }
        public string Solicitud_Diagnostico1_Descripcion { get; set; }
        public string Solicitud_Diagnostico2_Id { get; set; }
        public string Solicitud_Diagnostico2_Descripcion { get; set; }
        public string Solicitud_Diagnostico3_Id { get; set; }
        public string Solicitud_Diagnostico3_Descripcion { get; set; }
        public string Solicitud_Urgente { get; set; }
        public string Solicitud_Consultorio { get; set; }
        public string Solicitud_AreaMedica_Id { get; set; }
        public string Solicitud_AreaMedica_Descripcion { get; set; }
        public string Enterprise_Folio { get; set; }
        public System.DateTime Solicitud_Fecha { get; set; }
        public string Solicitud_Medico_ApellidoPaterno { get; set; }
        public string Solicitud_Medico_ApellidoMaterno { get; set; }
    }
}
