//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMDEVEntitiesSoLab : DbContext
    {
        public SMDEVEntitiesSoLab()
            : base("name=SMDEVEntitiesSoLab")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DHABIENTES> DHABIENTES { get; set; }
        public virtual DbSet<lab_catalogo> lab_catalogo { get; set; }
        public virtual DbSet<MEDICOS> MEDICOS { get; set; }
        public virtual DbSet<ESPECIALIDADES> ESPECIALIDADES { get; set; }
        public virtual DbSet<Lab_detalle> Lab_detalle { get; set; }
        public virtual DbSet<Lab_exp> Lab_exp { get; set; }
        public virtual DbSet<labinstrucciones> labinstrucciones { get; set; }
        public virtual DbSet<InventarioFarmacia> InventarioFarmacia { get; set; }
        public virtual DbSet<Receta_Detalle_2> Receta_Detalle_2 { get; set; }
        public virtual DbSet<RECETA_EXP_2> RECETA_EXP_2 { get; set; }
    }
}
