//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudPrestaciones
    {
        public int id { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public Nullable<int> id_subservicio { get; set; }
        public Nullable<int> clave_proveedor { get; set; }
        public string descripcion { get; set; }
        public string num_exp { get; set; }
        public string medico { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string folio { get; set; }
        public Nullable<int> sesiones { get; set; }
        public string nota { get; set; }
        public string ip_realiza { get; set; }
        public Nullable<int> estado { get; set; }
        public string diagnostico1 { get; set; }
        public string diagnostico2 { get; set; }
        public string diagnostico3 { get; set; }
        public string nota_filtro { get; set; }
        public string usuario_filtro { get; set; }
        public Nullable<System.DateTime> fecha_filtro { get; set; }
        public Nullable<int> id_subservicio2 { get; set; }
        public string descripcion2 { get; set; }
        public Nullable<int> id_subservicio3 { get; set; }
        public string descripcion3 { get; set; }
        public Nullable<int> adomicilio { get; set; }
        public string justificacion { get; set; }
    }
}
