//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;

    public class SolicitudLaboratorioExp
    {
        public Lab_exp LabExpediente { get; set; }
        public DHABIENTES DerechoHabiente { get; set; }
        public MEDICOS Medico { get; set; }
        public ESPECIALIDADES Especialidad { get; set; }
        public List<lab_catalogo> LabDetalle { get; set; }
        public lab_catalogo LabCatalogo { get; set; }
        public DateTime SysDatetimeNow { get; set; }
        public int EdadDHab { get; set; }

    }
    public class Lab_Detalle
    {
        public string lab_lab { get; set; }
        public string lab_id { get; set; }
        public Nullable<decimal> lab_instrucciones { get; set; }
    }

    public class Lab_Expediente
    {
        public string NUMEMP { get; set; }
        public string NUMAFIL { get; set; }
        public string expediente { get; set; }
        public DHABIENTES DHabiente { get; set; }
        public List<Lab_exp> LabExpediente { get; set; }
    }

    public class Lab_Solicitud
    {
        public string NUMEMP { get; set; }
        public string expediente { get; set; }
        public DHABIENTES DHabiente { get; set; }
        public List<SolicitudLab> LabSolicitud { get; set; }
    }

}