//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudLabEstudio
    {
        public int SolicitudId { get; set; }
        public int EstudioId { get; set; }
        public string EstudioDescripcion { get; set; }
        public string SolicitudExpediente { get; set; }
    }
}
