//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    
    public partial class SP_Trazabilidad_VE_Result1
    {
        public string Clave_Med_ { get; set; }
        public string Desc__Med_ { get; set; }
        public string Folio_VE_ { get; set; }
        public System.DateTime Fecha_VE { get; set; }
        public Nullable<int> Cant__VE_ { get; set; }
        public string Factura { get; set; }
        public string Lote { get; set; }
    }
}
