//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    
    public partial class SP_Trazabilidad_OC_Result2
    {
        public string Clave_Med_ { get; set; }
        public string Descripción_Med_ { get; set; }
        public string Folio_Req_ { get; set; }
        public Nullable<System.DateTime> Fecha_Req_ { get; set; }
        public Nullable<int> Cant__Req_ { get; set; }
        public string Folio_OC_ { get; set; }
        public Nullable<System.DateTime> Fecha_OC_ { get; set; }
        public Nullable<int> Cant__OC_ { get; set; }
        public Nullable<int> Cant__Pen_ { get; set; }
        public Nullable<double> P_U__OC { get; set; }
        public Nullable<int> Id { get; set; }
    }
}
