//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OrdenCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_OrdenCompra()
        {
            this.Tbl_DetalleOC = new HashSet<Tbl_DetalleOC>();
        }
    
        public int Id { get; set; }
        public string Clave { get; set; }
        public Nullable<int> Id_Requisicion { get; set; }
        public Nullable<int> Id_Proveedor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public string Forma_Pago { get; set; }
        public string Folio { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<bool> Cerrado { get; set; }
        public Nullable<int> Cuadro { get; set; }
        public string UsuarioNuevo { get; set; }
        public string IP_User { get; set; }
        public string NombreProveedor { get; set; }
        public Nullable<double> Total_OC { get; set; }
        public string OC_PorValidar { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha_Acuse { get; set; }
        public Nullable<System.DateTime> Fecha_AutorizaOC { get; set; }
        public string Usuario_AutorizaOC { get; set; }
        public Nullable<System.DateTime> Fecha_HacerOC { get; set; }
        public string Contrato { get; set; }
        public Nullable<double> Total_OC_iva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_DetalleOC> Tbl_DetalleOC { get; set; }
    }
}
