//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCarreras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCarreras()
        {
            this.TblEstudiosEmpleado = new HashSet<TblEstudiosEmpleado>();
        }
    
        public int IdCarrera { get; set; }
        public string Descripcion { get; set; }
        public int IdNivel { get; set; }
        public int IdEscuela { get; set; }
    
        public virtual TblNivelAcademico TblNivelAcademico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEstudiosEmpleado> TblEstudiosEmpleado { get; set; }
    }
}
