//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDetalleOrdenCompra
    {
        public int IdDetalleOrdenCompra { get; set; }
        public Nullable<int> IdOrdenCompra { get; set; }
        public Nullable<int> IdArticulo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> CostoUnitario { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
    }
}
