//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEstado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblEstado()
        {
            this.TblEmpleado = new HashSet<TblEmpleado>();
            this.TblEmpleado1 = new HashSet<TblEmpleado>();
            this.TblMunicipio = new HashSet<TblMunicipio>();
        }
    
        public int IdEstado { get; set; }
        public string clave { get; set; }
        public string nombre { get; set; }
        public string abrev { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<int> IdPais { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmpleado> TblEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEmpleado> TblEmpleado1 { get; set; }
        public virtual TblPais TblPais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMunicipio> TblMunicipio { get; set; }
    }
}
