//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEstudiosEmpleado
    {
        public int IdCarreraEmpleado { get; set; }
        public int Emp_NumEmp { get; set; }
        public int IdNivel { get; set; }
        public Nullable<int> IdCarrera { get; set; }
        public string Emp_Cedula { get; set; }
        public Nullable<System.DateTime> FechaExpedicion { get; set; }
        public Nullable<int> IdEscuela { get; set; }
    
        public virtual TblCarreras TblCarreras { get; set; }
        public virtual TblEmpleado TblEmpleado { get; set; }
        public virtual TblNivelAcademico TblNivelAcademico { get; set; }
    }
}
