//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmpleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblEmpleado()
        {
            this.TblAcceso = new HashSet<TblAcceso>();
            this.TblDocumentos = new HashSet<TblDocumentos>();
            this.TblEstudiosEmpleado = new HashSet<TblEstudiosEmpleado>();
            this.TblHijos = new HashSet<TblHijos>();
            this.TblKardex = new HashSet<TblKardex>();
            this.TblMovimientos = new HashSet<TblMovimientos>();
        }
    
        public int Emp_NumEmp { get; set; }
        public string Emp_RFC { get; set; }
        public string Emp_Nombre { get; set; }
        public string Emp_APaterno { get; set; }
        public string Emp_AMaterno { get; set; }
        public string Emp_CURP { get; set; }
        public Nullable<int> IdRegimen { get; set; }
        public string IdPuesto { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public string Emp_HoraEntrada { get; set; }
        public string Emp_HoraSalida { get; set; }
        public Nullable<int> IdTipoIngreso { get; set; }
        public string Emp_Ingresos { get; set; }
        public Nullable<int> IdUniforme { get; set; }
        public string Emp_Actividades { get; set; }
        public string Emp_Observaciones { get; set; }
        public string Emp_FechaNacimiento { get; set; }
        public string Emp_LugarNac { get; set; }
        public Nullable<int> Emp_Sexo { get; set; }
        public Nullable<int> Emp_EstadoCivil { get; set; }
        public Nullable<int> Emp_NumeroHijos { get; set; }
        public Nullable<int> Emp_CodigoPostal { get; set; }
        public Nullable<int> IdPais { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public Nullable<int> IdColonia { get; set; }
        public string Emp_Calle { get; set; }
        public string Emp_NumExt { get; set; }
        public string Emp_NumInt { get; set; }
        public string Emp_NumFijo { get; set; }
        public string Emp_NumCelular { get; set; }
        public Nullable<int> Emp_CodigoPostalFiscal { get; set; }
        public Nullable<int> IdPaisFiscal { get; set; }
        public Nullable<int> IdEstadoFiscal { get; set; }
        public Nullable<int> IdMunicipioFiscal { get; set; }
        public Nullable<int> IdColoniaFiscal { get; set; }
        public string Emp_CalleFiscal { get; set; }
        public string Emp_NumExtFiscal { get; set; }
        public string Emp_NumIntFiscal { get; set; }
        public string Emp_NumFijoFiscal { get; set; }
        public string Emp_NumCelularFiscal { get; set; }
        public string Emp_Edad { get; set; }
        public Nullable<bool> Emp_Lunes { get; set; }
        public Nullable<bool> Emp_Martes { get; set; }
        public Nullable<bool> Emp_Miercoles { get; set; }
        public Nullable<bool> Emp_Jueves { get; set; }
        public Nullable<bool> Emp_Viernes { get; set; }
        public Nullable<bool> Emp_Sabado { get; set; }
        public Nullable<bool> Emp_Domingo { get; set; }
        public string Emp_FechaIngreso { get; set; }
        public Nullable<System.DateTime> Emp_FechaBaja { get; set; }
        public Nullable<bool> Emp_Estatus { get; set; }
        public string Emp_NumEmpAccess { get; set; }
        public string Emp_NumRectoria { get; set; }
        public string EMail { get; set; }
        public Nullable<bool> Emp_Lunes2 { get; set; }
        public Nullable<bool> Emp_Martes2 { get; set; }
        public Nullable<bool> Emp_Miercoles2 { get; set; }
        public Nullable<bool> Emp_Jueves2 { get; set; }
        public Nullable<bool> Emp_Viernes2 { get; set; }
        public Nullable<bool> Emp_Sabado2 { get; set; }
        public Nullable<bool> Emp_Domingo2 { get; set; }
        public string Emp_HoraEntrada2 { get; set; }
        public string Emp_HoraSalida2 { get; set; }
        public Nullable<int> Emp_ExtencionTel { get; set; }
        public Nullable<int> NumEmp_Id { get; set; }
        public Nullable<bool> Emp_Baja { get; set; }
        public string IdCategoria { get; set; }
        public Nullable<int> UnidadMedica { get; set; }
        public Nullable<int> IdCategoriaSM { get; set; }
        public Nullable<int> IdPuestoSM { get; set; }
        public string Emp_IngresoBruto { get; set; }
        public Nullable<int> IdSubCategoria { get; set; }
        public Nullable<bool> Coordinador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAcceso> TblAcceso { get; set; }
        public virtual TblColonia TblColonia { get; set; }
        public virtual TblColonia TblColonia1 { get; set; }
        public virtual TblDepartamento TblDepartamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDocumentos> TblDocumentos { get; set; }
        public virtual TblEstado TblEstado { get; set; }
        public virtual TblEstado TblEstado1 { get; set; }
        public virtual TblMunicipio TblMunicipio { get; set; }
        public virtual TblMunicipio TblMunicipio1 { get; set; }
        public virtual TblPais TblPais { get; set; }
        public virtual TblPais TblPais1 { get; set; }
        public virtual TblPuesto TblPuesto { get; set; }
        public virtual TblRegimen TblRegimen { get; set; }
        public virtual TblUniforme TblUniforme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEstudiosEmpleado> TblEstudiosEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHijos> TblHijos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblKardex> TblKardex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMovimientos> TblMovimientos { get; set; }
    }
}
