//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHijos
    {
        public int IdHijo { get; set; }
        public string Nombre { get; set; }
        public string FechaNac { get; set; }
        public string Sexo { get; set; }
        public int Emp_NumEmp { get; set; }
        public Nullable<int> Edad { get; set; }
    
        public virtual TblEmpleado TblEmpleado { get; set; }
    }
}
