//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKardex
    {
        public int IdKardex { get; set; }
        public Nullable<int> Kar_REG { get; set; }
        public string Kar_MOV { get; set; }
        public Nullable<System.DateTime> Kar_INI { get; set; }
        public Nullable<System.DateTime> Kar_FIN { get; set; }
        public Nullable<System.DateTime> Kar_FRE { get; set; }
        public Nullable<System.DateTime> Kar_FSOL { get; set; }
        public string Kar_DIA { get; set; }
        public string Kar_HOR { get; set; }
        public string Kar_OBS { get; set; }
        public string Kar_PER { get; set; }
        public string Kar_SUB { get; set; }
        public string Kar_Emp { get; set; }
        public string Kar_REA { get; set; }
        public Nullable<System.DateTime> Kar_FCA { get; set; }
        public Nullable<System.DateTime> Kar_HCA { get; set; }
        public string Kar_DEP { get; set; }
        public string Kar_TIP { get; set; }
        public string Kar_STA { get; set; }
        public int ClaveMov { get; set; }
        public string ClaveNom { get; set; }
        public int IdDepartamento { get; set; }
        public int Emp_NumEmp { get; set; }
        public Nullable<int> IdMovimiento { get; set; }
        public Nullable<int> NumEmp_Autoriza { get; set; }
    
        public virtual TblEmpleado TblEmpleado { get; set; }
        public virtual TblKardexRHyNom TblKardexRHyNom { get; set; }
    }
}
