//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMovimientos
    {
        public int IdMovimiento { get; set; }
        public Nullable<System.DateTime> FechaRegreso { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<int> Emp_NumEmp { get; set; }
        public Nullable<int> TotalDias { get; set; }
        public Nullable<int> DiasDisponibles { get; set; }
        public Nullable<int> ClaveMov { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string Estado { get; set; }
    
        public virtual TblEmpleado TblEmpleado { get; set; }
        public virtual TblKardexRHyNom TblKardexRHyNom { get; set; }
    }
}
