//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotaFarmaco
    {
        public int IdNota { get; set; }
        public string NotaFarmaco { get; set; }
        public Nullable<System.DateTime> FechaNotaFarmaco { get; set; }
        public string MedicoRealizo { get; set; }
        public string IP_Realizo { get; set; }
        public string NUMEMP { get; set; }
        public Nullable<int> Riesgo { get; set; }
    }
}
