//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOrdenCompra
    {
        public int IdOrdenCompra { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Estatus { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Impuestos { get; set; }
        public Nullable<decimal> Impuestos1 { get; set; }
        public Nullable<decimal> Impuestos2 { get; set; }
        public Nullable<int> IdRequisicion { get; set; }
    }
}
