//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRequisicion
    {
        public int IdRequisicion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdUsuario { get; set; }
        public string IPUsuario { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> DiasTranscurrido { get; set; }
        public Nullable<bool> Baja { get; set; }
        public string TipoAlmacen { get; set; }
    }
}
