//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTallasUniformes
    {
        public int IdTalla { get; set; }
        public string NombreUniforme { get; set; }
        public int IdUniforme { get; set; }
    
        public virtual TblUniforme TblUniforme { get; set; }
    }
}
