//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTriage
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Descripcion { get; set; }
        public string Expediente { get; set; }
        public string ip_realiza { get; set; }
        public string UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaLlamado { get; set; }
        public string ColorConsulta { get; set; }
        public string ConsultaEspecial { get; set; }
        public string SV_PAdiastolica { get; set; }
        public string SV_FC { get; set; }
        public string SV_FR { get; set; }
        public string SV_Temperatura { get; set; }
        public string SV_SO2 { get; set; }
        public string SV_Glucosa { get; set; }
        public string SV_Glasgow { get; set; }
        public string SV_Peso { get; set; }
        public string SV_Talla { get; set; }
        public string SV_PAsistolica { get; set; }
        public string NombrePaciente { get; set; }
        public string EdadPaciente { get; set; }
        public string SexoPaciente { get; set; }
        public string VigenciaPaciente { get; set; }
        public string EstatusConsulta { get; set; }
        public string MedicoLlama { get; set; }
        public string ip_realizaMedico { get; set; }
        public Nullable<int> ConsultorioMedico { get; set; }
        public string PasarASoap { get; set; }
        public string NotaEvolucion { get; set; }
    }
}
