//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int UsuarioId { get; set; }
        public string Usu_User { get; set; }
        public string Usu_Pass { get; set; }
        public string Usu_Nombre { get; set; }
        public System.DateTime Usu_FecAlt { get; set; }
        public Nullable<byte> RolId { get; set; }
        public bool Usu_Status { get; set; }
        public bool Baja { get; set; }
    }
}
