//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.OrdenCompra = new HashSet<OrdenCompra>();
        }
    
        public int UsuarioId { get; set; }
        public string Usu_User { get; set; }
        public string Usu_Pass { get; set; }
        public string Usu_Nombre { get; set; }
        public System.DateTime Usu_FecAlt { get; set; }
        public Nullable<byte> RolId { get; set; }
        public bool Usu_Status { get; set; }
        public bool Baja { get; set; }
        public Nullable<int> Caja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompra> OrdenCompra { get; set; }
    }
}
