//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UanlSISM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValeEntrada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ValeEntrada()
        {
            this.Detalle_VE = new HashSet<Detalle_VE>();
        }
    
        public int id { get; set; }
        public string clave { get; set; }
        public Nullable<int> id_Requisicion { get; set; }
        public Nullable<int> id_ordencompra { get; set; }
        public Nullable<int> id_valesalida { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> Fecha_Mod { get; set; }
        public string Factura { get; set; }
        public string Remision { get; set; }
        public int id_usuario { get; set; }
        public byte status { get; set; }
        public Nullable<byte> tipo { get; set; }
        public Nullable<int> id_ConceptoEntrada { get; set; }
        public string UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_VE> Detalle_VE { get; set; }
        public virtual Requisicion Requisicion { get; set; }
    }
}
